//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahsoka.Test.Control.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CanTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CanTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ahsoka.Test.Control.Properties.CanTestResources", typeof(CanTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSION &quot;&quot;
        ///
        ///NS_ :
        ///	BA_
        ///	BA_DEF_
        ///	BA_DEF_DEF_
        ///	BA_DEF_DEF_REL_
        ///	BA_DEF_REL_
        ///	BA_DEF_SGTYPE_
        ///	BA_REL_
        ///	BA_SGTYPE_
        ///	BO_TX_BU_
        ///	BU_BO_REL_
        ///	BU_EV_REL_
        ///	BU_SG_REL_
        ///	CAT_
        ///	CAT_DEF_
        ///	CM_
        ///	ENVVAR_DATA_
        ///	EV_DATA_
        ///	FILTER
        ///	NS_DESC_
        ///	SGTYPE_
        ///	SGTYPE_VAL_
        ///	SG_MUL_VAL_
        ///	SIGTYPE_VALTYPE_
        ///	SIG_GROUP_
        ///	SIG_TYPE_REF_
        ///	SIG_VALTYPE_
        ///	VAL_
        ///	VAL_TABLE_
        ///
        ///BS_:
        ///
        ///BU_: DBG CONTROLLER IO MOTOR SENSOR
        ///
        ///
        ///BO_ 100 DRIVER_HEARTBEAT: 1 CONTROLLER
        /// SG_ DRIVER_HEARTBEAT_cmd : 0|8@1+ (1,0) [0|0] &quot;&quot; SENSOR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestFile {
            get {
                return ResourceManager.GetString("TestFile", resourceCulture);
            }
        }
    }
}
